version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
  stayalive-api:
    image: stayalive-api:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
volumes:
  mongodb_data_container:
