version: '3'
services:
  # Install MongoDB Database
  mongodb-stayalive:
    container_name: mongodb-stayalive
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  # Install Redis Database
  redis-stayalive:
    container_name: redis-stayalive
    image: redis:latest
    ports:
      - 6379:6379
  # Install the API
  stayalive-api:
    image: stayalive-api:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - mongodb-stayalive
      - redis-stayalive
volumes:
  mongodb_data:
    driver: local
