name: Node CI

on: [ push, pull_request ]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Start MongoDB Database
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-db: stayalive
          mongodb-port: 27017
      - name: Start Redis Database
        uses: supercharge/redis-github-action@1.5.0
      - name: Inject .env file
        run: |
          echo ${{ secrets.ENV_FILE }} | base64 --decode > .env
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test