name: Create Release + Docker Hub

on:
  push:
    branches:
      - master


jobs:
  build-and-deploy-back:
    name: Build and deploy back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: package-version
        uses: nyaa8/package-version@v1.0.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          tags: stayalive/stayalive-api:${{ env.PACKAGE_VERSION }}, stayalive/stayalive-api:latest
          push: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: Version ${{ env.PACKAGE_VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

